workflows:
  telegram-ios-simulator:
    name: Telegram iOS • simulator .app for App Preview
    instance_type: mac_mini_m1       # любой macOS-runner с Xcode 16.2
    environment:
      xcode: 16.2                    # ⇠ ключевая строчка: жёстко просим Xcode 16.2
      vars:
        BAZEL_TARGET: //Telegram:TelegramApp
        BAZEL_CPU: ios_sim_arm64     # симулятор на Apple Silicon
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main              # или master, как у тебя
          include: true

    scripts:
      # 1. Зависимости
      - name: Install Bazel & tools
        script: |
          brew install bazelisk ninja coreutils
          # заглушка, чтобы Bazel не ругался на configuration-repository
          mkdir -p build-input/configuration-repository
          touch build-input/configuration-repository/WORKSPACE

      # 2. Сборка .app для симулятора
      - name: Build .app with Bazel
        script: |
          bazelisk build $BAZEL_TARGET \
            --apple_platform_type=ios \
            --cpu=$BAZEL_CPU

      # 3. Упаковать найденную .app в zip (App Preview читает zip)
      - name: Package .app
        script: |
          mkdir -p output
          APP_PATH=$(find bazel-out -type d -name '*.app' | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "❌ .app not found – Bazel layout поменялся?" && exit 1
          fi
          echo "Found .app at $APP_PATH"
          (cd "$APP_PATH"/.. && zip -r "$CM_BUILD_DIR/output/Telegram.app.zip" "$(basename "$APP_PATH")")

    artifacts:
      - output/Telegram.app.zip      # ⬅️ появится в «Artifacts» и станет доступен для App Preview
