name: Build Telegram-iOS via Bazel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout Telegram-iOS
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Homebrew and dependencies
      run: |
        brew update
        brew install bazelisk cmake ninja coreutils

    - name: Build Telegram app for simulator
      run: |
        export DEVELOPER_DIR=$(xcode-select -p)
        export SDKROOT=$(xcrun --sdk iphonesimulator --show-sdk-path)
        bazelisk build //Telegram:TelegramApp --apple_platform_type=ios --cpu=ios_sim_arm64

    - name: Zip .app
      run: |
        mkdir -p output
        APP_PATH=$(find bazel-out -type d -name '*.app' | head -n 1)
        echo "App found at: $APP_PATH"
        zip -r output/Telegram.app.zip "$APP_PATH"

    - name: Upload .app artifact
      uses: actions/upload-artifact@v4
      with:
        name: Telegram-app
        path: output/Telegram.app.zip
